# Generated by Django 4.2.30 on 2026-06-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('BMS Demo Request', 'BMS Demo Request'), ('Pricing Inquiry', 'Pricing / Plan Inquiry'), ('Subscription Inquiry', 'Subscription Inquiry'), ('Business Setup Help', 'Business Setup Help'), ('Enterprise Plan Inquiry', 'Enterprise Plan Inquiry'), ('Technical Support', 'Technical Support'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], max_length=80)),
                ('preferred_plan', models.CharField(blank=True, choices=[('Basic Plan', 'Basic Plan'), ('Professional Plan', 'Professional Plan'), ('Business Plan', 'Business Plan'), ('Enterprise Plan', 'Enterprise Plan'), ('Not Sure', 'Not Sure')], max_length=80, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
