# Generated by Django 4.2.30 on 2026-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
